/*
 * generated by Xtext 2.25.0
 */
package com.mike.berezhkov.huawei;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CPoCPRuntimeModule extends AbstractCPoCPRuntimeModule {
}
